// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FontSizer
{
    internal sealed partial class Vsix
    {
        public const string Id = "f7198797-d75d-4a7b-93c6-7bb56907735b";
        public const string Name = "Font Sizer 2.0";
        public const string Description = @"An easy way to change the font sizes in the editor and Visual Studio environment.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "font, presentation, zoom";
    }
}
