// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FontSizer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidIncreaseFontSizePackageString = "1099b5c0-7023-4762-9cd9-008d1219c716";
        public static Guid guidIncreaseFontSizePackage = new Guid(guidIncreaseFontSizePackageString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int EditorGroup = 0x1020;
        public const int EnvironmentGroup = 0x1021;
        public const int MyMenu = 0x1030;
        public const int cmdidIncreaseFontSize = 0x0100;
        public const int cmdidDecreaseFontSize = 0x0200;
        public const int cmdidIncreaseEnviornmentFontSize = 0x0300;
        public const int cmdidDecreaseEnviornmentFontSize = 0x0400;
    }
}